---
- hosts: myServers
  become: yes

  vars:
      project_name: "Devylawyer's Blog"
      project_path: /home/ubuntu/devyapp
      sites_available: /etc/nginx/sites-available
      sites_enabled: /etc/nginx/sites-enabled
      sites_available_devylawyer: /etc/nginx/sites-available/devylawyer
      sites_enabled_devylawyer: /etc/nginx/sites-enabled/devylawyer

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        update_cache: true
        state: latest

    - name: Get Nodejs gpg key
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    - name: Install Nodejs version 10 binary
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
        state: present

    - name: install nodejs
      apt: name=nodejs
    - name: Clone the repository
      git:
        repo: https://github.com/ChiamakaObitube/devyapp.git
        dest: "{{ project_path }}"
    - name: Delete nginx default file
      file:
        path: "{{ sites_available }}/default"
        state: absent
    - name: Configure nginx server
      shell: |
          echo "
            server {
                listen 80;
                server_name localhost;
                access_log /var/log/nginx/nginx.conf.log;
                charset utf-8;

                location / {
                  proxy_pass http://localhost:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                }
              }
                > {{ sites_available_devylawyer }}
    - name: Update nginx symlink
      file:
        src={{ sites_available_devylawyer }}
        dest={{ sites_enabled_devylawyer }}
        state=link
    - name: install NPM
      shell: npm i
      args:
        chdir: /home/ubuntu/devyapp

  handlers:
    - name: start Nginx
      service: name=nginx state=started