---
  - hosts: localhost
    remote_user: ubuntu
    become_method: sudo
    become: true

    vars:
      - homeDir: /home/ubuntu
      - appDir : AutoMart
      - repo: AutoMart
      - account: ChiamakaObitube
      - privateKey: /home/devylawyer/.ssh/id_rsa  
      - project_name: "AutoMart"
      - project_path: /home/ubuntu/AutoMart
      - sites_available: /etc/nginx/sites-available
      - sites_enabled: /etc/nginx/sites-enabled
      - sites_available_automart: /etc/nginx/sites-available/automart
      - sites_enabled_automart: /etc/nginx/sites-enabled/automart
      - PM2_PATH: $PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu/


    tasks:

    - name: Create APP Directory
      file: path={{homeDir}}/{{appDir}} state=directory

    - name: Copy Private Key
      copy: src={{privateKey}} dest={{homeDir}} mode=0600

    - name: Get Nodejs gpg key
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    - name: Install Nodejs version 10 binary
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
        state: present
    - name: Install Node
      apt:
        name: nodejs
        state: present
    - name: Clone the repository
      git:
        repo: https://github.com/ChiamakaObitube/AutoMart.git
        dest: "{{ project_path }}"
    - name: Install node packages
      shell: |
        npm install nodejs
        npm install
    - name: Install nginx
      apt:
        name: nginx
      
        state: latest
    - name: Delete nginx default file
      file:
        path: "{{ sites_available }}/default"
        state: absent
    - name: Configure nginx server
      shell: |
          echo "
            server {
              listen 80;
                location / {
                  proxy_pass http://localhost:3000/;
                  }
                }
                " > {{ sites_available_automart }}

    - name: start Nginx
      service: name=nginx state=restarted
    - name: Install pm2 to run app in background
      shell: npm install pm2 -g
    - name: Create pm2 start script
      shell: |
        cd /home/ubuntu/AutoMart
        echo '
          {
              "apps": [{
              "name": "AutoMart",
              "script": "npm",
              "args": "start"
              }]
          }
        ' > start_script.config.json
    - name: Start app with pm2
      shell: |
        cd /home/ubuntu/AutoMart
        sudo pm2 start ./start_script.config.json
        sleep 10
        sudo pm2 startup
        sudo env PATH={{PM2_PATH}}
        sudo pm2 save

