apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-php
spec:
  selector:
    matchLabels:
      run: kubernetes-php
  template:
    metadata:
      labels:
        run: kubernetes-php
    spec:
      containers:
        - name: demo
          image: chiamakaobitube/docker-php-hello-world
          ports:
            - containerPort: 80